Exclude `composer/xdebug-handler`
`XdebugHandler` is used in `php-cs-fixer` file, but it can't be processed properly by `composer-unused` (using custom config file):

Fatal error: Uncaught Error: Call to undefined method PhpParser\Node\Expr\Closure::getParts() in dev-tools/vendor/composer-unused/symbol-parser/src/Parser/PHP/DefinedSymbolCollector.php:65